#!/usr/bin/env python
"""
rss2dent is an RSS to identi.ca agent. It pulls feeds from a feed url, and 
posts the result to identi.ca. The link to the original feed article is
converted to a 'short url', and the title is chopped at 140 characters.
"""

import os
import sys
import time
import logging
import feedparser
from f2dlibs import Storage, TimeoutError, FeedContainer, NullLoggingHandler
from f2dlibs import identica, jfilters, timeout, cmdln
from jinja2 import Environment
from ConfigParser import RawConfigParser

###
### classes
class CommandParser(cmdln.Cmdln):
    name = "feed2dent"
    version = "0.2"

    def __init__(self, *args, **kwargs):
        cmdln.Cmdln.__init__(self, *args, **kwargs)
        # ensure that if no logger is created, we don't puke
        # just appends, so it won't overwrite existing
        self.logger = logging.getLogger('cmdparser')
        self.logger.addHandler(NullLoggingHandler())

    def get_optparser(self):
        parser = cmdln.Cmdln.get_optparser(self)
        parser.add_option("-v", action="count", dest="verbosity", default=0,
            help="Set verbose logging. Additional instances add verbosity.")
        return parser

    def precmd(self, arg):
        if self.options.verbosity > 2:
            verbosity = logging.DEBUG
        elif self.options.verbosity == 1:
            verbosity = logging.INFO
        else:
            verbosity = logging.WARNING
        # reconfigure the default logger level
        # this propagates down to children
        logging.getLogger().setLevel(verbosity)
        return arg

    @cmdln.option("-f", "--fetch-only", action="store_true", dest="nodent",
        default=False, help="Fetch feeds but do post a dent.")
    def do_dent(self, subcmd, opts, *content):
        """Send the specified text directly to identi.ca, as a simple dent.

        usage: 
            dent CONTENT...

        ${cmd_option_list}
        """
        text = ' '.join(content).strip()
        if len(text) < 1:
            self.logger.critical('No content to post. Doing nothing.')
            return 1
        self.logger.debug('processing simple dent: "%s"', text)
        if opts.nodent == True:
            self.logger.debug('no-dent set. not sending...')
        else:
            identica.dent(config.identica, text)

    def do_list(self, subcmd, opts, *feedname):
        """list feeds from the config file

        ${cmd_usage}
        If no FEEDNAME(s) provided, run for all feeds.

        ${cmd_option_list}
        """
        counter = 0
        if len(feedname) > 0:
            feeds = [x for x in feedname if x in config.feeds.keys()]
        else:
            feeds = config.feeds.keys()
        feeds.sort()
        fc = FeedContainer(config.general.dat_path)
        fc.load()
        for x in feeds:
            counter += 1
            print '[%2d] name: %s' % (counter, x)
            print '     url:  %s' % config.feeds[x]
            if x in config.templates:
                print '     tpl:  %s' % config.templates[x]
            else:
                print '     tpl:  %s' % config.templates['default']
            if fc.loaded == True and x in fc.feeds:
                print '     feed-type: %s' % fc.feeds[x].version
                print '     last-update: %s' % \
                    time.strftime('%Y-%m-%d %H:%M', fc.feeds[x].updated)

    @cmdln.option("-f", "--fetch-only", action="store_true", dest="nodent",
        default=False, help="Fetch feeds but do post a dent.")
    def do_feed(self, subcmd, opts, *feedname):
        """parse FEEDNAME(s) feed and post to identi.ca

        ${cmd_usage}
        If no FEEDNAME(s) provided, run for all feeds.

        ${cmd_option_list}
        """
        fc = FeedContainer(config.general.dat_path)
        fc.load()
        if len(feedname) > 0:
            for x in feedname:
                if x not in config.feeds.keys():
                    print 'feed name "%s" not in config.' % x
                else:
                    feedit(x, fobj=None, nodent=opts.nodent)
        else:
            # remove feeds no longer in config
            if fc.loaded == True:
                for x in fc.feeds.keys():
                    if x not in config.feeds.keys():
                        self.logger.info('feed "%s" no longer in config.', x)
                        self.logger.info('deleting feed "%s".', x)
                        del fc.feeds[x]
            # operate on feeds
            for x in config.feeds.keys():
                if x in fc.feeds:
                    fc.feeds[x] = feedit(x, fobj=fc.feeds[x], nodent=opts.nodent)
                else:
                    fc.feeds[x] = feedit(x, fobj=None, nodent=opts.nodent)
            fc.save()


###
### helper function defs
def feedit(feedname, fobj=None, nodent=False):
    """Main entry point for rss2dent"""
    logger = logging.getLogger('main')
    jenv = Environment()
    jenv.filters['shortenurl'] = jfilters.shortenurl
    # get rss feed
    try:
        logger.debug('fetching feed "%s"', feedname)
        if fobj and hasattr(fobj,'modified'):
            logger.debug('conditional fetch: modified date')
            newfobj = timeout(10, feedparser.parse, 
                              config.feeds[feedname], 
                              modified=fobj.modified)
        else:
            newfobj = timeout(10, feedparser.parse, 
                              config.feeds[feedname])
    except TimeoutError:
        logger.critical('timed out reading feed "%s". giving up', feedname)
        return fobj

    if not newfobj:
        logger.critical('feed "%s" was empty!', feedname)
        return fobj
    else:
        logger.debug('feed retrieved')

    if newfobj.status == 304:
        logger.info('no new feed data since last fetch')
        # return old object, preserving older last modified stamp
        return fobj

    ## start processing feed
    if nodent == True:
        # do nothing but return new object.
        logger.debug('no-dent set. not sending...')
        return newfobj
    else:
        posts_made = 0
        entries = newfobj.entries
        entries.reverse()
        # look for new feed items
        for entry in entries:
            match = False
            if fobj:
                for oldentry in fobj.entries:
                    if entry.id == oldentry.id:
                        match = True
            if match == False:
                if feedname in config.templates:
                    tplstring = config.templates[feedname]
                else:
                    tplstring = config.templates['default']
                # new entry. do dent
                template = jenv.from_string(tplstring)
                text = template.render(url=entry.link, title=entry.title)
                # do dent
                identica.dent(config.identica, text)
                posts_made += 1
        if posts_made > 0:
            logger.info('posted %d dents', posts_made)
        else:
            logger.info('no new feed data')
        # return new obj
        return newfobj


###
### main
if __name__ == '__main__':
    # load config vars
    if not os.path.exists('config.ini'):
        sys.exit('no config file found. exiting.')
    cfgp = RawConfigParser()
    cfgp.read('config.ini')
    config = Storage()
    for section in cfgp.sections():
        config[section] = Storage()
        for left,right in cfgp.items(section):
            config[section][left] = right
    # setup logging -- we will set the log level later
    logging.basicConfig(
        format="%(asctime)s : %(levelname)-8s %(message)s",
        datefmt='%Y-%m-%d %H:%M')
    # start command parser
    feed2dent = CommandParser()
    ret = feed2dent.main()
    sys.exit(ret)

